import type { Metadata } from "next";
import {Footer} from "./components/Footer";
import {AuthHeader} from "./components/authHeader";
import {UnauthHeader} from "./components/unauthHeader";
import { Geist, Geist_Mono, Bodoni_Moda  } from "next/font/google";
import {cookies} from "next/headers";
import "./globals.css";


const bodoni = Bodoni_Moda({
  subsets: ['latin'],
  weight: ['400', '700'], // choose the weights you want
  variable: '--font-bodoni', // optional: expose as CSS variable
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const storedCookies = await cookies();
  const token = storedCookies.get("token");
  const isAuthenticated = token !== undefined;
  console.log("isAuthenticated", isAuthenticated);
  
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        {/* <link href="https://cdn.jsdelivr.net/npm/flowbite@3.1.2/dist/flowbite.min.css" rel="stylesheet" /> */}
      </head>
      <body
        className={` ${bodoni.variable} antialiased bg-[var(--background)]`}
      >
       
       {isAuthenticated ? <AuthHeader/> : <UnauthHeader />}
        {children}
        <Footer/>
       

      <script src="https://cdn.jsdelivr.net/npm/flowbite@3.1.2/dist/flowbite.min.js"></script>
      </body>
    </html>
  );
}

