import type { Metadata } from "next";
import {Footer} from "./components/Footer";
import {AuthHeader} from "./components/authHeader";
import {UnauthHeader} from "./components/unauthHeader";
import { Geist, Geist_Mono } from "next/font/google";
import {cookies} from "next/headers";
import QueryProvider from "@/providers/QueryProvider";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const storedCookies = await cookies();
  const token = storedCookies.get("token");
  const isAuthenticated = token !== undefined;
  console.log("isAuthenticated", isAuthenticated);
  
  return (
    <html lang="en" className="scroll-smooth">
      <head>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
       
        <QueryProvider>
          {isAuthenticated ? <AuthHeader/> : <UnauthHeader />}
          {children}
        </QueryProvider>
        <Footer/>
       

      </body>
    </html>
  );
}

